id: P010516
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG5962
  title: ལྷ་ལྡན་རྭ་ས་འཕྲུལ་སྣང་གཙུག་ལག་ཁང་གི་དཀར་ཆག
  author: ''
  volumes:
    02055c6712664a0b8733448ee3d86f17:
      image_group_id: I1KG5972
      title: ''
      volume_number: 1
      total_pages: 188
      base_file: v001.txt
