id: ID3D71399
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T20:17:28+00:00'
last_modified: '2022-06-08T14:10:29.399765+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG5962
  title: ལྷ་ལྡན་རྭ་ས་འཕྲུལ་སྣང་གཙུག་ལག་ཁང་གི་དཀར་ཆག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    71A1:
      image_group_id: I1KG5972
      title: ''
      total_pages: 188
      order: 1
      base_file: 71A1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
