id: ID3D71399
legacy_id: P010516
ocr_import_info:
  bdrc_scan_id: W1KG5962
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T20:16:08'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T17:31:49.019036+00:00'
last_modified: 2022-09-01 01:31:56.712439
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG5962
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW1KG5962
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ལྷ་ལྡན་རྭ་ས་འཕྲུལ་སྣང་གཙུག་ལག་ཁང་གི་དཀར་ཆག
  author: ཞྭ་སྒབ་པ་དབང་ཕྱུག་བདེ་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.8940279472843451
  ocr_word_median_confidence_index: 0.9599999785423279
quality: null
bases:
  I1KG5972:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG5972
      total_pages: 188
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG5972.txt
    statistics:
      ocr_word_median_confidence_index: 0.9599999785423279
      ocr_word_mean_confidence_index: 0.8940279472843451
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
